name: Build iOS (Unsigned)

on:
  push:
    branches: ["main", "feature/*"]
  workflow_dispatch:

defaults:
  run:
    working-directory: smart_call_assistant

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Clean Project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: smart_call_assistant/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('smart_call_assistant/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Build iOS (No Codesign)
        run: |
          # Ensuring the ios directory is ready
          flutter build ios --release --no-codesign

      - name: Create Payload directory
        run: mkdir Payload

      - name: Move App to Payload
        run: mv build/ios/iphoneos/Runner.app Payload/

      - name: Zip Payload
        run: zip -r Runner.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: smart_call_assistant/Runner.ipa
