name: Build iOS (Unsigned)

on:
  push:
    branches: ["main", "feature/*"]
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod --version

      - name: Clean Project
        run: flutter clean

      - name: Get Dependencies
        run: flutter pub get

      - name: Pre-build iOS Config
        run: |
          cd ios
          rm -f Flutter/Generated.xcconfig
          rm -f Flutter/flutter_export_environment.sh
          cd ..

      - name: Build iOS (No Codesign)
        run: flutter build ios --release --no-codesign

      - name: Create IPA (Payload Method)
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sca-ios-release
          path: Runner.ipa
